global:
  scrape_interval: 30s
  evaluation_interval: 30s
  external_labels:
    cluster: "${PROM_CLUSTER}"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:${PROMETHEUS_PORT}']

  - job_name: 'broker'
    file_sd_configs:
      - files:
          - '/etc/prometheus/targets.json'

  - job_name: 'burrow'
    metrics_path: /metrics
    static_configs:
      - targets: ['burrow:${BURROW_PORT}']
